AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chouseisan-reminder

Parameters:
  ChouseisanNotifySlackUrl:
    Type : AWS::SSM::Parameter::Value<String>

Resources:
  ChouseisanReminderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: chouseisan-reminder-function
      CodeUri: src/notify_1st_message/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 10
      Environment:
        Variables:
          TZ: Asia/Tokyo
          INCOMMING_WEBHOOK_URL: !Ref ChouseisanNotifySlackUrl
      Events:
        NotifySlack:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 1-7 * ? *) # 日本時間で毎月1-7日のAM9時

  ChouseisanReminderFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ChouseisanReminderFunction}"

  ChouseisanSaveDeadlineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: chouseisan-save-deadline-function
      CodeUri: src/save_deadline/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 10
      Environment:
        Variables:
          TZ: Asia/Tokyo
          REMINDER_TABLE_NAME: !Ref ChouseisanReminderTable
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Events:
        WorkflowApi:
          Type: Api
          Properties:
            Path: /reminder
            Method: post

  ChouseisanSaveDeadlineFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ChouseisanSaveDeadlineFunction}"

  ChouseisanReminderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: chouseisan-reminder-table
      KeySchema:
        - AttributeName: deadline
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: deadline
          AttributeType: N
      TimeToLiveSpecification:
        AttributeName: expiration
        Enabled: true
      BillingMode: PAY_PER_REQUEST

Outputs:
  SaveDeadlineApi:
    Description: "save deadline api"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/reminder/"
